# Generated by Django 2.2.3 on 2019-07-21 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('q_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.CharField(max_length=500)),
                ('a_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Question')),
            ],
        ),
    ]
