# Generated by Django 2.2.3 on 2019-07-21 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20190721_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answers',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='title',
        ),
    ]
