# Generated by Django 2.2.3 on 2019-07-21 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_auto_20190721_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='author',
        ),
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
    ]
