# Generated by Django 2.2.3 on 2019-07-21 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_auto_20190721_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Just',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='review.Post')),
            ],
        ),
    ]
